### ISSUE TITLE
Typo on install page

### ISSUE THREAD

**Issue by kellsnollenberger** [RichardBray/muffin#2]
On the install page (http://richbray.me/muffin/#inst) it says that you can 

"Add your custom sass in 'css/sass/custom/_style.scss', then type 'sh wath.sh' to         watch it. In a new window/tab type 'jekyll' to watch your site."

I believe it should be 

```
sh watch.sh
```

**Comment by RichardBray** [comment]
Hi Kells, thanks for making me aware of the spelling mistake I've fixed it now. Also–I'm really really sorry about the late reply. There should be an email notification for github issues.
