### ISSUE TITLE
gulp not generating js and css files

### ISSUE THREAD

**Issue by connor11528** [RichardBray/muffin#6]
I downloaded chocolate chip, ran `npm install` then `gulp` in one terminal and `jekyll serve -w` in the other. Gulp did not create `css/style.css` or `js/scripts.min.js` So when I fire up localhost:400 I get the error:

```
GET http://jasonshark:4000/css/style.css 404 (Not Found) 
GET http://jasonshark:4000/js/scripts.min.js 404 (Not Found) 
```

Somehow `gulpfile.js` isn't creating these files for me..

**Comment by RichardBray** [comment]
Man that sucks. I'll fix that ASAP and let you know when it's done.

**Comment by noorhammad** [comment]
@jasonshark @RichardBray I've submitted a pull request to fix this issue. 

JS: Gulp was not configured correctly
CSS: @jasonshark you need to save css/style.scss at least once before style.css will be generated.

**Comment by RichardBray** [comment]
@noorhammad Thanks buddy. I've accepted the pull request.
